# Generated by Django 3.2.3 on 2021-05-15 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('post_category', models.CharField(default='RELIGION', max_length=15, verbose_name='post category')),
                ('post_title', models.CharField(max_length=100, verbose_name='post title')),
                ('post_content', models.TextField(verbose_name='post content')),
                ('post_keyword', models.CharField(max_length=100, verbose_name='post keyword')),
                ('post_cover', models.ImageField(upload_to='post/image/', verbose_name='post cover')),
                ('post_viewed', models.PositiveIntegerField(default=0, verbose_name='post viewed')),
                ('post_activated', models.BooleanField(default=False, verbose_name='post activated')),
                ('post_created', models.DateTimeField(auto_now=True, verbose_name='post created')),
                ('post_status', models.CharField(default='DRAFT', max_length=9, verbose_name='post status')),
                ('slug', models.SlugField(unique=True, verbose_name='post link')),
            ],
            options={
                'verbose_name_plural': 'Article',
                'db_table': 'post_title',
                'ordering': ['-post_created'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id', 'uuid'], name='id_index'),
        ),
    ]
