# Generated by Django 3.2.3 on 2021-05-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date_created'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_created',
            new_name='post_date_created',
        ),
    ]
