# Generated by Django 3.2.3 on 2021-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210516_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('SPORT', 'Sport'), ('RELIGION', 'Religion'), ('POLITIQUE', 'Politique'), ('COMMUNIQUE', 'Communiqué'), ('BOUAKE_NEWS', 'Bouaké News'), ('INTERNATIONAL', 'International'), ('SOCIETE_CULTURE', 'Société & Culture')], default='RELIGION', max_length=15, verbose_name='post category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date_created',
            field=models.DateField(auto_now=True, verbose_name='post created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=9, verbose_name='post status'),
        ),
    ]
