# Generated by Django 3.2.3 on 2021-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210526_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_activated',
            field=models.BooleanField(default=False, verbose_name='Activatez le post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(verbose_name='Contenu du post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_cover',
            field=models.ImageField(upload_to='post/image/', verbose_name='Importer image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date_created',
            field=models.DateField(auto_now=True, verbose_name='Post cree'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_keyword',
            field=models.CharField(max_length=100, verbose_name='mot cle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publier')], default='DRAFT', max_length=9, verbose_name='Status du post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100, verbose_name='Titre du post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='post vu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Lien du post'),
        ),
    ]
