# Generated by Django 3.2.4 on 2021-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210610_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('SPORT', 'Cote d_ivoire'), ('RELIGION', 'Afrique'), ('POLITIQUE', 'Europe'), ('COMMUNIQUE', 'Asie'), ('BOUAKE_NEWS', 'Amerique'), ('INTERNATIONAL', 'Oceanie')], default='RELIGION', max_length=15, verbose_name='post category'),
        ),
    ]
