# Generated by Django 3.2.4 on 2021-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('SPORT', 'Sport'), ('RELIGION', 'Religion'), ('POLITIQUE', 'Politique'), ('COMMUNIQUE', 'Communiqué'), ('BOUAKE_NEWS', 'Bouaké News'), ('INTERNATIONAL', 'International'), ('SOCIETE_CULTURE', 'Société & Culture')], default='RELIGION', max_length=15, verbose_name='post category'),
        ),
    ]
